# Generated by Django 4.1.5 on 2023-01-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_teacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='teacher_file',
            field=models.BooleanField(default=False),
        ),
    ]
