# Generated by Django 4.1.5 on 2023-01-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_file_teacher_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
