# Generated by Django 4.1.5 on 2023-01-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_file_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='university.course'),
            preserve_default=False,
        ),
    ]
