# Generated by Django 4.1.5 on 2023-01-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_file_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='teacher',
            field=models.CharField(default='teacher', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_link',
            field=models.URLField(default='fake.zoom-link.com', max_length=255),
            preserve_default=False,
        ),
    ]
