# Generated by Django 4.1.5 on 2023-01-05 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_appointment_teacher_appointment_zoom_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='body',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 5, 22, 48, 29, 763372)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 5, 22, 48, 45, 366677)),
            preserve_default=False,
        ),
    ]
