# Generated by Django 4.1.5 on 2023-01-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_rename_created_at_answer_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='zoom_link',
            field=models.CharField(max_length=255),
        ),
    ]
