# Generated by Django 4.1.5 on 2023-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_alter_appointment_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='teacher',
            field=models.CharField(default='teacher', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateField(),
        ),
    ]
