# Generated by Django 4.1.5 on 2023-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_alter_appointment_teacher_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='creator',
            field=models.CharField(default='teacher', max_length=255),
            preserve_default=False,
        ),
    ]
