# Generated by Django 4.1.5 on 2023-01-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_student_received_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
