# Generated by Django 4.1.5 on 2023-01-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_remove_teacher_user_delete_student_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
    ]
