# Generated by Django 4.1.5 on 2023-01-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='redeemed',
        ),
    ]
